version: '3'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
  local-stack:
    image: localstack/localstack:0.12.4
    ports:
      - "4566-4576:4566-4576"
  mysql:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      #    - ./docker/db/data:/var/lib/mysql
      - ./docker/myqsl/my.cnf:/etc/mysql/conf.d/my.cnf
    #    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
