AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvName:
    Type: String
  EncryptionKey:
    Type: String
    Description: ex. arn:aws:kms:...
Mappings:
  EnvMap:
    gray:
      BranchName: 'dev'
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Sub artifacts-${EnvName}
        EncryptionKey:
          Id: !Ref EncryptionKey
          Type: KMS
      Name: !Sub sample-${EnvName}
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/codepipeline-role
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Owner: AWS
            Provider: CodeCommit
            Version: 1
          RunOrder: 1
          Configuration:
            PollForSourceChanges: false
            RepositoryName: sample-api
            BranchName:
              Fn::FindInMap:
                - EnvMap
                - Ref: EnvName
                - BranchName
          InputArtifacts: []
          OutputArtifacts:
          # Artifact の Name は Actions の Name と連動する
          - Name: SourceArtifact
          RoleArn: arn:aws:iam::933351349976:role/codecommit-role # ここはアカウント毎に固定
      - Name: CreateChangeSet
        Actions:
          - Name: CodePipelineApi
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: SourceArtifact
            Configuration:
              ActionMode: CHANGE_SET_REPLACE
              StackName: !Sub infra-resources-sample-codepipeline-api-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-codepipeline-api-${EnvName}
              TemplatePath: SourceArtifact::cloudformation/sample/sample-codepipeline-api.yaml
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
              ParameterOverrides: !Sub |
                {
                  "EnvName": "${EnvName}",
                  "EncryptionKey": "${EncryptionKey}"
                }
            RunOrder: 1
          - Name: CodePipelineSPA
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: SourceArtifact
            Configuration:
              ActionMode: CHANGE_SET_REPLACE
              StackName: !Sub infra-resources-sample-codepipeline-spa-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-codepipeline-spa-${EnvName}
              TemplatePath: SourceArtifact::cloudformation/sample/codepipeline-spa.yaml
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
              ParameterOverrides: !Sub |
                {
                  "EnvName": "${EnvName}",
                  "EncryptionKey": "${EncryptionKey}"
                }
            RunOrder: 1
          - Name: IAM
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: SourceArtifact
            Configuration:
              ActionMode: CHANGE_SET_REPLACE
              Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
              StackName: !Sub infra-resources-sample-iam-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-iam-${EnvName}
              TemplatePath: SourceArtifact::cloudformation/sample/iam.yaml
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
              ParameterOverrides: !Sub |
                {
                  "EnvName": "${EnvName}"
                }
            RunOrder: 1
          - Name: CloudFrontSPA
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: SourceArtifact
            Configuration:
              ActionMode: CHANGE_SET_REPLACE
              StackName: !Sub infra-resources-sample-cloudfront-spa-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-cloudfront-spa-${EnvName}
              TemplatePath: SourceArtifact::cloudformation/sample/cloudfront-spa.yaml
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
              ParameterOverrides: !Sub |
                {
                  "EnvName": "${EnvName}"
                }
            RunOrder: 1
          - Name: DynamoDB
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: SourceArtifact
            Configuration:
              ActionMode: CHANGE_SET_REPLACE
              StackName: !Sub infra-resources-sample-dynamodb-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-dynamodb-${EnvName}
              TemplatePath: SourceArtifact::cloudformation/sample/dynamodb.yaml
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
              ParameterOverrides: !Sub |
                {
                  "EnvName": "${EnvName}"
                }
            RunOrder: 1
          - Name: ECS
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            InputArtifacts:
              - Name: SourceArtifact
            Configuration:
              ActionMode: CHANGE_SET_REPLACE
              Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
              StackName: !Sub infra-resources-sample-ecs-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-ecs-${EnvName}
              TemplatePath: SourceArtifact::cloudformation/sample/ecs.yaml
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
              ParameterOverrides: !Sub |
                {
                  "EnvName": "${EnvName}"
                }
            RunOrder: 1
            #          - Name: SQS
            #            ActionTypeId:
            #              Category: Deploy
            #              Owner: AWS
            #              Provider: CloudFormation
            #              Version: '1'
            #            InputArtifacts:
            #              - Name: SourceArtifact
            #            Configuration:
            #              ActionMode: CHANGE_SET_REPLACE
            #              StackName: !Sub infra-resources-sample-sqs-${EnvName}
            #              ChangeSetName: !Sub infra-resources-sample-sqs-${EnvName}
            #              TemplatePath: SourceArtifact::cloudformation/sample/sample-sqs.yaml
            #              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            #              ParameterOverrides: !Sub |
            #                {
            #                  "EnvName": "${EnvName}"
            #                }
            #            RunOrder: 1
            #          - Name: S3
            #            ActionTypeId:
            #              Category: Deploy
            #              Owner: AWS
            #              Provider: CloudFormation
            #              Version: '1'
            #            InputArtifacts:
            #              - Name: SourceArtifact
            #            Configuration:
            #              ActionMode: CHANGE_SET_REPLACE
            #              StackName: !Sub infra-resources-sample-s3-${EnvName}
            #              ChangeSetName: !Sub infra-resources-sample-s3-${EnvName}
            #              TemplatePath: SourceArtifact::cloudformation/sample/sample-s3.yaml
            #              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            #              ParameterOverrides: !Sub |
            #                {
            #                  "EnvName": "${EnvName}"
            #                }
            #            RunOrder: 1
      - Name: ApproveChangeSets
        Actions:
          - Name: Approve
            ActionTypeId:
              Category: Approval
              Owner: AWS
              Provider: Manual
              Version: '1'
            RunOrder: 1
      - Name: ExecuteChangeSet
        Actions:
          - Name: CodePipelineApi
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              ActionMode: CHANGE_SET_EXECUTE
              StackName: !Sub infra-resources-sample-codepipeline-api-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-codepipeline-api-${EnvName}
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            RunOrder: 1
          - Name: CodePipelineSPA
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              ActionMode: CHANGE_SET_EXECUTE
              StackName: !Sub infra-resources-sample-codepipeline-spa-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-codepipeline-spa-${EnvName}
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            RunOrder: 1
          - Name: IAM
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              ActionMode: CHANGE_SET_EXECUTE
              StackName: !Sub infra-resources-sample-iam-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-iam-${EnvName}
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            RunOrder: 1
          - Name: CloudFrontSPA
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              ActionMode: CHANGE_SET_EXECUTE
              StackName: !Sub infra-resources-sample-cloudfront-spa-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-cloudfront-spa-${EnvName}
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            RunOrder: 1
          - Name: DynamoDB
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              ActionMode: CHANGE_SET_EXECUTE
              StackName: !Sub infra-resources-sample-dynamodb-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-dynamodb-${EnvName}
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            RunOrder: 1
          - Name: ECS
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              ActionMode: CHANGE_SET_EXECUTE
              StackName: !Sub infra-resources-sample-ecs-${EnvName}
              ChangeSetName: !Sub infra-resources-sample-ecs-${EnvName}
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            RunOrder: 1
            #          - Name: SQS
            #            ActionTypeId:
            #              Category: Deploy
            #              Owner: AWS
            #              Provider: CloudFormation
            #              Version: '1'
            #            Configuration:
            #              ActionMode: CHANGE_SET_EXECUTE
            #              StackName: !Sub infra-resources-sample-sqs-${EnvName}
            #              ChangeSetName: !Sub infra-resources-sample-sqs-${EnvName}
            #              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            #            RunOrder: 1
            #          - Name: S3
            #            ActionTypeId:
            #              Category: Deploy
            #              Owner: AWS
            #              Provider: CloudFormation
            #              Version: '1'
            #            Configuration:
            #              ActionMode: CHANGE_SET_EXECUTE
            #              StackName: !Sub infra-resources-sample-s3-${EnvName}
            #              ChangeSetName: !Sub infra-resources-sample-s3-${EnvName}
            #              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformation-role
            #            RunOrder: 1
